<Project Sdk="Microsoft.NET.Sdk">

  <!-- 公共属性见根目录 Directory.Build.props -->
  <ItemGroup>
    <ProjectReference Include="..\LMLoader.Api\LMLoader.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LMLoader.Core.Tests" />
  </ItemGroup>

</Project>
