<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <!-- 包版本统一在根目录 Directory.Packages.props(CPM)管理 -->
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="HarmonyX" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LMLoader.Core\LMLoader.Core.csproj" />
    <ProjectReference Include="..\..\src\LMLoader.Distribution.Thunderstore\LMLoader.Distribution.Thunderstore.csproj" />
  </ItemGroup>

</Project>
